let products = [
    {
      "id": 1,
      "title": "Math",
      "description": "Math classes",
      "price": 15,
      "image": "./images/math.png",
      "availableInventory": 5,
      "rating": 4,
      "time" : "4 till 6",
      "days" : "Sunday - Monday - Wednesday",
      "teacher" : "Mr.Justin",
      "duration" : "2 Hours",
      "location" : "London",
      "gif": "./images/mathg.gif"
    },
    {
      "id": 2,
      "title": "English",
      "description": "English classes",
      "price": 15,
      "image": "./images/english.png",
      "availableInventory": 5,
      "rating": 4,
      "time" :  "4 till 6",
      "days" : "Sunday - Monday - Wednesday",
      "teacher" : "Mrs.Engie",
      "duration" : "2 Hours",
      "location" : "London",
      "gif": "./images/englishg.gif"
    },
    {
      "id": 3,
      "title": "Physics",
      "description": "Physics classes",
      "price": 15,
      "image": "./images/physics.png",
      "availableInventory": 5,
      "rating": 3,
      "time" :  "4 till 6",
      "days" : "Sunday - Monday - Wendnesday",
      "teacher" : "Mr.Shawn",
      "duration" : "2 Hours",
      "location" : "London",
      "gif": "./images/physicsg.gif"
    },
    {
      "id": 4,
      "title": "Chemistry",
      "description": "Chemistry classes",
      "price": 15,
      "image": "./images/chemistry.png",
      "availableInventory": 5,
      "rating": 2,
      "time" :  "4 till 6",
      "days" : "Sunday - Monday - Wednesday",
      "teacher" : "Mr.Clark",
      "duration" : "2 Hours",
      "location" : "London",
      "gif": "./images/chmistryg.gif"
    },
    {
      "id": 5,
      "title": "Biology",
      "description": "Biology classes",
      "price": 15,
      "image": "./images/biology.png",
      "availableInventory": 5,
      "rating": 4,
      "time" :  "4 till 6",
      "days" : "Sunday - Monday - Wednesday",
      "teacher" : "Mrs.Pattie",
      "duration" : "2 Hours",
      "location" : "London",
      "gif": "./images/biog.gif"
    },
    {
      "id": 6,
      "title": "Football",
      "description": "Show your talent in 11v11 matches",
      "price": 20,
      "image": "./images/football.jpg",
      "availableInventory": 5,
      "rating": 5,
      "time" :  "2 till 5",
      "days" : "Thursday - Friday - Saturday",
      "teacher" : "Coach.Mark",
      "duration" : "3 Hours",
      "location" : "Manchester",
      "gif": "./images/goal.gif"
    },
    {
      "id": 7,
      "title": "Basketabll",
      "description": "Show how high you can jump",
      "price": 20,
      "image": "./images/basketball.jpg",
      "availableInventory": 5,
      "rating": 4,
      "time" : "2 till 5",
      "days" : "Thursday - Friday - Saturday",
      "teacher" : "Coach.Anna",
      "duration" : "3 Hours",
      "location" : "Manchester",
      "gif": "./images/basketballg.gif"
    },
    {
      "id": 8,
      "title": "Tennis",
      "description": "It is all about the wrist swing",
      "price": 20,
      "image": "./images/tennis.png",
      "availableInventory": 5,
      "rating": 3,
      "time" :  "2 till 5",
      "days" : "Thursday - Friday - Saturday",
      "teacher" : "Coach.Anjela",
      "duration" : "3 Hours",
      "location" : "Manchester",
      "gif": "./images/tennisg.gif"
    },
    {
      "id": 9,
      "title": "Swimming",
      "description": "How long can you hold your breath under water",
      "price": 20,
      "image": "./images/swimming.jpg",
      "availableInventory": 5,
      "rating": 3,
      "time" : "2 till 5",
      "days" : "Thursday - Friday - Saturday",
      "teacher" : "Coach.Michael",
      "duration" : "3 Hours",
      "location" : "Manchester",
      "gif": "./images/swimmingg.gif"
    },
    {
      "id": 10,
      "title": "Archery",
      "description": "Aim is the Key",
      "price": 20,
      "image": "./images/archery.jpg",
      "availableInventory": 5,
      "rating": 2,
      "time" :  "2 till 5",
      "days" : "Thursday - Friday - Saturday",
      "teacher" : "Coach.June",
      "duration" : "3 Hours",
      "location" : "Manchester",
      "gif": "./images/archeryg.gif"
    },
    {
      "id": 11,
      "title": "Drama Club",
      "description": "Think you can act?",
      "price": 8,
      "image": "./images/drama.png",
      "availableInventory": 5,
      "rating": 5,
      "time" :  "3 till 5",
      "days" : "Tuesday",
      "teacher" : "Mr.Joey",
      "duration" : "2 Hours",
      "location" : "Birmingham",
      "gif": "./images/dramag.gif"
    },
    {
      "id": 12,
      "title": "Music Club",
      "description": "Lets sing",
      "price": 8,
      "image": "./images/music.png",
      "availableInventory": 5,
      "rating": 5,
      "time" :  "3 till 5",
      "days" : "Tuesday",
      "teacher" : "Mr.Justin",
      "duration" : "2 Hours",
      "location" : "Birmingham",
      "gif": "./images/singg.gif"
    },
    {
      "id": 14,
      "title": "Poetry Club",
      "description": "Poetry is the key",
      "price": 8,
      "image": "./images/poetry.png",
      "availableInventory": 5,
      "rating": 4,
      "time" :  "3 till 5",
      "days" : "Tuesday",
      "teacher" : "Mrs.Karen",
      "duration" : "2 Hours",
      "location" : "Birmingham",
      "gif": "./images/poetryg.gif"
    },
    {
      "id": 15,
      "title": "Craft Club",
      "description": "Imagination",
      "price": 8,
      "image": "./images/craft.png",
      "availableInventory": 5,
      "rating": 3,
      "time" :  "3 till 5",
      "days" : "Tuesday",
      "teacher" : "Mr.John",
      "duration" : "2 Hours",
      "location" : "Birmingham",
      "gif": "./images/craftg.gif"
    },
    {
      "id": 16,
      "title": "Cooking Club",
      "description": "Make excellent meals",
      "price": 8,
      "image": "./images/cooking.png",
      "availableInventory": 5,
      "rating": 5,
      "time" :  "3 till 5",
      "days" : "Tuesday",
      "teacher" : "Mr.Mendes",
      "duration" : "2 Hours",
      "location" : "Birmingham",
      "gif": "./images/cooking.gif"
    }
  ]